required-players: 2
max-players: 8
countdown-seconds: 30
lobby-spawn:
  world: 'world'
  x: 100
  y: 100
  z: 100
  yaw: -180
  pitch: 0
arenas:
  0:
    world: 'world'
    x: 100
    y: 100
    z: 100
    yaw: -180
    pitch: 0
    spawns:
      red:
        x: 100
        y: 100
        z: 100
        yaw: -180
        pitch: 0
      blue:
        x: 100
        y: 100
        z: 100
        yaw: -180
        pitch: 0
    beds:
      red:
        x: 100
        y: 100
        z: 100
        facing: north
      blue:
        x: 100
        y: 100
        z: 100
        facing: south