required-players: 2
countdown-seconds: 30
lobby-spawn:
  world: 'world'
  x: 100
  y: 100
  z: 100
  yaw: -180
  pitch: 0
arenas:
  0:
    world: 'world'
    x: 100
    y: 100
    z: 100
    yaw: -180
    pitch: 0